namespace: clothing
items:
  trainer_leggings:
    material: LEATHER_LEGGINGS
    item_model: minecraft:armor/trainer/leggings
    name: Trainer Leggings
    equippable:
      slot: LEGS
      asset_id: minecraft:trainer
  trainer_chestplate:
    material: LEATHER_CHESTPLATE
    item_model: minecraft:armor/trainer/chestplate
    name: Trainer Chestplate
    equippable:
      slot: CHEST
      asset_id: minecraft:trainer
  trainer_boots:
    material: LEATHER_BOOTS
    item_model: minecraft:armor/trainer/boots
    name: Trainer Boots
    equippable:
      slot: FEET
      asset_id: minecraft:trainer
